# Generated by Django 5.0.4 on 2024-06-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='user_id',
        ),
    ]
