# Generated by Django 5.0.4 on 2024-06-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
